on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container: 
      image: puklu/stm32f3discovery-dev-env:1.0.0
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure Git
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
  
      - name: Create build directory
        run: mkdir -p build

      - name: Configure project with cmake
        run: |
          cd build
          cmake ..

      - name: Check formatting using clang-format
        run: |
          cd build
          make format
          git diff --exit-code 
          
      - name: Build the project
        run: |
          cd build
          make
