on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container: 
      image: puklu/stm32f3discovery-dev-env:1.0.0
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Create build directory
        run: mkdir -p build

      - name: Configure project with cmake
        run: |
          cd build
          cmake ..

      - name: Run clang-format
        run: |
          cd build
          make clang-format
          git diff --quiet || (echo "Code is not formatted correctly!" && exit 1) 
          
      - name: Build the project
        run: |
          cd build
          make
