on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container: 
      image: puklu/stm32f3discovery-dev-env:1.0.0
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Create build directory
        run: mkdir -p build

      - name: Check Git and directory structure
        run: |
          pwd  # Print current directory
          ls -la  # List all files in the current directory
          cd build
          pwd  # Print current directory after moving into build
          ls -la  # List all files inside the build directory  

      - name: Configure project with cmake
        run: |
          cd build
          cmake ..

      - name: Run clang-format
        run: |
          cd build
          make clang-format
          git diff --exit-code 
          
      - name: Build the project
        run: |
          cd build
          make
